### ISSUE TITLE
Best practice: Update gap value

### ISSUE THREAD

**Issue by MortimerNeuss** [yckart/jquery.fixer.js#3]
What is the best way to update the gap? I currently re-init the whole part by 

            $('.elem').fixer({
                gap: 70
            });

Is this the best way?

**Comment by yckart** [comment]
I have updated the code, now you can update the options like this:

``` javascript
var options = {
  gap: 0
};

$('.node').fixer(options);

options.gap = 70;
```

**Comment by ghost** [comment]
That worked. Until I tested it on iOS.
Your change in line 30 somehow broke the function of the main Fixing Function.

does not work on iOS:
options = $.extend(options, defaults);

works on iOS:
options = $.extend({}, defaults, options);

Do you experience the same effect?
